apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - minio.yaml
  # secrets.yaml managed separately (not in git)

images:
  - name: registry.wejoona.com/usdc-wallet-api
    newTag: 67b802b18cc04f11c0e0b7cb2b1126c252a2ab4d
