apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - minio.yaml
  # secrets.yaml managed separately (not in git)

images:
  - name: registry.wejoona.com/usdc-wallet-api
    newTag: 191d7bacdfdcce98c0819137ec1ce601922d5956
