apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - minio.yaml
  # secrets.yaml managed separately (not in git)

images:
  - name: registry.wejoona.com/usdc-wallet-api
    newTag: 3c310faed59f184ea3ef02430cc8bdc22ed79b42
