/**
 * Application error codes for consistent client error handling.
 * Mobile app uses these to show localized error messages.
 */
export const ERROR_CODES = {
  // Auth errors (1xxx)
  AUTH_INVALID_OTP: 'E1001',
  AUTH_OTP_EXPIRED: 'E1002',
  AUTH_OTP_LOCKED: 'E1003',
  AUTH_TOKEN_EXPIRED: 'E1004',
  AUTH_TOKEN_INVALID: 'E1005',
  AUTH_PHONE_NOT_FOUND: 'E1006',
  AUTH_ACCOUNT_SUSPENDED: 'E1007',
  AUTH_ACCOUNT_DEACTIVATED: 'E1008',

  // PIN errors (2xxx)
  PIN_INCORRECT: 'E2001',
  PIN_LOCKED: 'E2002',
  PIN_TOKEN_EXPIRED: 'E2003',
  PIN_TOKEN_INVALID: 'E2004',
  PIN_ALREADY_SET: 'E2005',
  PIN_NOT_SET: 'E2006',

  // Transfer errors (3xxx)
  TRANSFER_INSUFFICIENT_FUNDS: 'E3001',
  TRANSFER_LIMIT_EXCEEDED: 'E3002',
  TRANSFER_RECIPIENT_NOT_FOUND: 'E3003',
  TRANSFER_SELF_TRANSFER: 'E3004',
  TRANSFER_AMOUNT_TOO_LOW: 'E3005',
  TRANSFER_AMOUNT_TOO_HIGH: 'E3006',
  TRANSFER_BLOCKED: 'E3007',

  // Deposit errors (4xxx)
  DEPOSIT_PROVIDER_UNAVAILABLE: 'E4001',
  DEPOSIT_AMOUNT_TOO_LOW: 'E4002',
  DEPOSIT_AMOUNT_TOO_HIGH: 'E4003',
  DEPOSIT_FAILED: 'E4004',
  DEPOSIT_OTP_INVALID: 'E4005',

  // KYC errors (5xxx)
  KYC_ALREADY_SUBMITTED: 'E5001',
  KYC_DOCUMENT_INVALID: 'E5002',
  KYC_FACE_MISMATCH: 'E5003',
  KYC_EXPIRED_DOCUMENT: 'E5004',

  // Withdrawal errors (6xxx)
  WITHDRAWAL_LIMIT_EXCEEDED: 'E6001',
  WITHDRAWAL_INSUFFICIENT_FUNDS: 'E6002',
  WITHDRAWAL_PROVIDER_UNAVAILABLE: 'E6003',
  WITHDRAWAL_AMOUNT_TOO_LOW: 'E6004',
  WITHDRAWAL_AMOUNT_TOO_HIGH: 'E6005',
  WITHDRAWAL_FAILED: 'E6006',
  WITHDRAWAL_RATE_UNAVAILABLE: 'E6007',

  // Payment Link errors (7xxx)
  PAYMENT_LINK_NOT_FOUND: 'E7001',
  PAYMENT_LINK_EXPIRED: 'E7002',
  PAYMENT_LINK_INACTIVE: 'E7003',
  PAYMENT_LINK_SELF_PAY: 'E7004',
  PAYMENT_LINK_ALREADY_PAID: 'E7005',
  PAYMENT_LINK_INSUFFICIENT_FUNDS: 'E7006',

  // Savings Pot errors (7.5xxx)
  SAVINGS_POT_NOT_FOUND: 'E7501',
  SAVINGS_POT_LOCKED: 'E7502',
  SAVINGS_POT_INSUFFICIENT_FUNDS: 'E7503',
  SAVINGS_POT_LIMIT_REACHED: 'E7504',

  // Card errors (8xxx)
  CARD_NOT_FOUND: 'E8001',
  CARD_ALREADY_EXISTS: 'E8002',
  CARD_FROZEN: 'E8003',
  CARD_CANCELLED: 'E8004',
  CARD_SPENDING_LIMIT_EXCEEDED: 'E8005',
  CARD_PROVIDER_UNAVAILABLE: 'E8006',

  // Recurring Transfer errors (8.5xxx)
  RECURRING_TRANSFER_NOT_FOUND: 'E8501',
  RECURRING_TRANSFER_LIMIT_REACHED: 'E8502',
  RECURRING_TRANSFER_CANNOT_UPDATE: 'E8503',
  RECURRING_TRANSFER_EXECUTION_FAILED: 'E8504',

  // Bank Linking errors (8.7xxx)
  BANK_LINKING_UNAVAILABLE: 'E8701',

  // Bulk Payment errors (8.8xxx)
  BULK_PAYMENTS_UNAVAILABLE: 'E8801',

  // System errors (9xxx)
  RATE_LIMITED: 'E9001',
  MAINTENANCE_MODE: 'E9002',
  INTERNAL_ERROR: 'E9999',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
